### ISSUE TITLE
Doesn't handle nested events in order

### ISSUE THREAD

**Issue by codewinch** [popchathq/popstart#17]
Popstart binds to events in different orders (appears to be according to DOM order) than what would be expected.

For example, if you have a div:

```html
<div click=outerFunc>
      <button click=moreSpecificFunction>Click Me</button>
</div>
```

What actually happens is that outerFunc gets triggered first, but really the more deeply nested function should be triggered first.

The moreSpecificFunction should trigger a button click event before outerFunc is called. (Also, there should probably be a stopPropagation/preventDefault utility plugin.)

**Comment by popchathq** [comment]
(in progress)

**Comment by popchathq** [comment]
Brief summary of changes:

1. introduce `__.sortBasedOnNesting(a, b)` which returns 0, 1, or -1 based on whether `a` contains `b`.
2. rewrite `__.el(selector, container)` to use `__.sortBasedOnNesting(a, b)` so that `__.el` now returns a *sorted* list of matches, which lets us bind in the correct order.
3. added `__.stop` which simply stops propagation so you can add that to your function list in any context where you might want to stop propagation upward in the DOM.
4. added `, true` to [`el.addEventListener()`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) call, which enables `useCapture`. From the explanation at the `addEventListener` documentation (above):
> A boolean value indicating whether events of this type will be dispatched to the registered listener before being dispatched to any EventTarget beneath it in the DOM tree. Events that are bubbling upward through the tree will not trigger a listener designated to use capture. Event bubbling and capturing are two ways of propagating events that occur in an element that is nested within another element, when both elements have registered a handle for that event. The event propagation mode determines the order in which elements receive the event. See DOM Level 3 Events and JavaScript Event order for a detailed explanation. If not specified, useCapture defaults to false.
